environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_GENERATOR: "Visual Studio 15 2017 Win64"
      ADDITIONAL_CMAKE_ARGS: "-DImageApprovals_ENABLE_QT5_INTEGRATION=OFF"
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      CC: gcc-7
      CXX: g++-7
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      CC: gcc-9
      CXX: g++-9

platform:
  - x64

configuration: Release

install:
  - ps: >-
      if($isWindows) {
        $env:Path = "C:\Python37;C:\Python37\Scripts;" + $env:Path;
        python -m pip install --upgrade pip;
        python -m pip install conan;
      } elseif($isLinux) {
        sudo apt install -y python3-pip $($env:CC);
        sudo pip3 install conan;
      }

  - sh: sudo apt install -y qt5-default xvfb
  - sh: export DISPLAY=':99.0'
  - sh: Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

  # Run conan user only on windows
  # cmake is run from powershell below,
  # and for some reason when there's no
  # conan profile, on windows, powershell
  # execption is thrown and the build fails.
  - cmd: conan user 

  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - cmd: git submodule update --init
  
  - sh: (cd $APPVEYOR_BUILD_FOLDER; git submodule update --init)

clone_depth: 1

build_script:
  - ps: mkdir build | Out-Null
  - ps: mkdir install | Out-Null
  - ps: cd build
  - ps: cmake .. -DCMAKE_BUILD_TYPE="$env:CONFIGURATION" -DCMAKE_INSTALL_PREFIX="$(pwd)/../install" $env:ADDITIONAL_CMAKE_ARGS
  - ps: cmake --build . --config "$env:CONFIGURATION"
  - ps: cmake --build . --config "$env:CONFIGURATION" --target install
  - ps: cd ..

test_script:
  - ps: cd build
  - ps: ctest --verbose