environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CMAKE_GENERATOR: "Visual Studio 14 2015 Win64"
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      CC: gcc-7
      CXX: g++-7
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      CC: gcc-9
      CXX: g++-9
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      CC: clang-6.0
      CXX: clang++-6.0

platform:
  - x64

configuration: Release

install:
  - ps: >-
      if($isWindows) {
        $env:Path = "C:\Python37;C:\Python37\Scripts;" + $env:Path;
        python -m pip install --upgrade pip;
        python -m pip install conan;
      } elseif($isLinux) {
        sudo apt install -y python3-pip $($env:CC);
        sudo pip3 install conan;
      }
  # Run conan user only on windows
  # cmake is run from powershell below,
  # and for some reason when there's no
  # conan profile, on windows, powershell
  # execption is thrown and the build fails.
  - cmd: conan user 

  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - cmd: git submodule update --init
  
  - sh: (cd $APPVEYOR_BUILD_FOLDER; git submodule update --init)

clone_depth: 1

build_script:
  - ps: mkdir build | Out-Null
  - ps: mkdir install | Out-Null
  - ps: cd build
  - ps: cmake .. -DCMAKE_BUILD_TYPE="$env:CONFIGURATION" -DCMAKE_INSTALL_PREFIX="$(pwd)/../install"
  - ps: cmake --build . --config "$env:CONFIGURATION"
  - ps: cmake --build . --config "$env:CONFIGURATION" --target install
  - ps: cd ..

test_script:
  - ps: cd build
  - ps: ctest --verbose