language: cpp

dist: bionic
python: "3.6"

compiler:
- gcc
- clang

os:
- linux

addons:
  apt:
    packages:
    - python3-pip
    - python3-setuptools

install:
- pip3 install --user conan
- conan user

script:
- mkdir --parents build/release/
- cd build/release/
- cmake ../.. -DCMAKE_BUILD_TYPE=Release
- cmake --build
- ctest --verbose
