#ifndef IMAGEAPPROVALS_VERSION_HPP_INCLUDED
#define IMAGEAPPROVALS_VERSION_HPP_INCLUDED

#define ImageApprovals_VERSION_MAJOR 0
#define ImageApprovals_VERSION_MINOR 1
#define ImageApprovals_VERSION_PATCH 0

#define ImageApprovals_VERSION_STR "0.1.0"

#endif // IMAGEAPPROVALS_VERSION_HPP_INCLUDED
